#!/usr/bin/env bash
set -e

cd $(dirname $0)/..

echo "==> Validating ci for version ${VERSION} ..."

go generate
GOPATH= go mod tidy

source ./scripts/version

if [ -n "$DIRTY" ]; then
    echo Git is dirty
    git status
    git diff
    exit 1
fi
