#!/usr/bin/env bash

BIN_NAME="api-test"
BUILD_DIR=$(dirname $0)"/../build/bin"
ARTIFACTS_DIR=$(dirname $0)"/../dist/artifacts"

if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
    DIRTY="-dirty"
fi

GIT_TAG=$(git tag -l --contains HEAD | head -n 1)

if [ -n "$VERSION" ]; then
    VERSION="$VERSION${DIRTY}"
elif [ -n "$GIT_TAG" ]; then
    VERSION="$GIT_TAG${DIRTY}"
else
    COMMIT=$(git rev-parse --short HEAD)
    VERSION="${COMMIT}${DIRTY}"
fi

TAG=${TAG:-${VERSION}}
REPO=${REPO:-rawmind}

if echo $TAG | grep -q dirty; then
    TAG=dev
fi
