name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  create:
    tags:
jobs:
  ci:
    runs-on: ubuntu-18.04
    container: golang:1.17.9-alpine3.15
    steps:
    - name: Install prerequisites
      run: |
        apk -U add bash git gcc musl-dev make docker-cli curl ca-certificates
    - uses: actions/checkout@v3
    - name: Build
      run: |
        git config --global --add safe.directory /__w/api-test/api-test
        make build
        echo "Deploying tag ${{ github.ref }}"
    - name: Build cross binaries
      if: ${{ github.event_name == 'create' && github.event.ref_type == 'tag' }}
      run: CROSS=1 make build
    - name: Validate
      if: ${{ github.event_name == 'create' && github.event.ref_type == 'tag' }}
      run: make validate-ci
    - name: Package and Release
      if: ${{ github.event_name == 'create' && github.event.ref_type == 'tag' }}
      env:
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
      run: make package
