name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-18.04
    container: golang:1.17.9-alpine3.15
    steps:
    - name: Install prerequisites
      run: |
        apk -U add bash git gcc musl-dev make docker-cli curl ca-certificates
    - uses: actions/checkout@v3
    - name: Build
      run: |
        export GIT_CEILING_DIRECTORIES=/__w
        git config --global --add safe.directory /__w/api-test/api-test
        ls -la
        CROSS=1 make build
        echo "Deploying tag ${{ github.ref }}"
