name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: git config --global --add safe.directory /go/src/github.com/rawmind0/api-test
    - name: Build
      run: CROSS=1 make docker-build
