name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-18.04
    container: golang:1.17.9-alpine3.15
    steps:
    - run: apk -U add bash git gcc musl-dev make docker-cli curl ca-certificates
    - uses: actions/checkout@v3
      with:
        path: /go/src/github.com/rawmind0/api-test
    - name: Build
      run: CROSS=1 make build
